import Testing
@testable import LetItBrewCore
@Test func transactionOrdersInstallBoundaries() throws { var calls: [String] = []; try AgentInstallTransaction.install(preflightPureTransform: { calls.append("preflight"); return 1 }, persistExactTarget: { _ in calls.append("persist") }, commitVendorMutation: { _ in calls.append("commit") }); #expect(calls == ["preflight", "persist", "commit"]) }
@Test func transactionDoesNotCommitAfterPersistenceFailure() { var committed = false; #expect(throws: TestFailure.self) { try AgentInstallTransaction.install(preflightPureTransform: { 1 }, persistExactTarget: { _ in throw TestFailure() }, commitVendorMutation: { _ in committed = true }) }; #expect(!committed) }
@Test func transactionOrdersUninstallBoundaries() throws { var calls: [String] = []; try AgentInstallTransaction.uninstall(removeOwnedOrProveAbsent: { calls.append("remove") }, clearExactTarget: { calls.append("clear") }); #expect(calls == ["remove", "clear"]) }
@Test func transactionNeverPersistsAfterPreflightFailure() { var persisted = false; #expect(throws: TestFailure.self) { try AgentInstallTransaction.install(preflightPureTransform: { throw TestFailure() }, persistExactTarget: { _ in persisted = true }, commitVendorMutation: { (_: Int) in }) }; #expect(!persisted) }
@Test func transactionKeepsPersistedRecordWhenVendorCommitFails() { var persisted = false; #expect(throws: TestFailure.self) { try AgentInstallTransaction.install(preflightPureTransform: { 1 }, persistExactTarget: { _ in persisted = true }, commitVendorMutation: { _ in throw TestFailure() }) }; #expect(persisted) }
@Test func transactionNeverClearsAfterRemovalFailure() { var cleared = false; #expect(throws: TestFailure.self) { try AgentInstallTransaction.uninstall(removeOwnedOrProveAbsent: { throw TestFailure() }, clearExactTarget: { cleared = true }) }; #expect(!cleared) }
@Test func transactionLeavesRemovalCompleteWhenClearFails() { var removed = false; #expect(throws: TestFailure.self) { try AgentInstallTransaction.uninstall(removeOwnedOrProveAbsent: { removed = true }, clearExactTarget: { throw TestFailure() }) }; #expect(removed) }
private struct TestFailure: Error {}
